services:
  - type: web
    name: vychytavky-cz
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 2 --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /healthz
    autoDeploy: false
